### ISSUE TITLE
Design: Projekt Termine

### ISSUE THREAD

**Issue by florianguenther** [jtm-ev/website#60]
![bildschirmfoto 2016-06-23 um 13 25 26](https://cloud.githubusercontent.com/assets/214641/16301503/fee50f64-3945-11e6-9cc1-ff79c6a69c2b.png)

**Comment by ishockwave** [comment]
Closed in https://github.com/jtm-ev/website/commit/1e2ba30bb8ac012d3f2e1a5e1af0dc95a862486a
