### ISSUE TITLE
WYSIWYG asset_url für Bilder

### ISSUE THREAD

**Issue by ishockwave** [jtm-ev/website#66]
Wo werden die Bilder gesetzt? Ich find da nix
![bildschirmfoto 2016-07-11 um 22 09 20](https://cloud.githubusercontent.com/assets/12819416/16745018/4ce82b52-47b4-11e6-8020-e659e77be02b.png)

**Comment by florianguenther** [comment]
das ist fest im 'content' als html drin, das können wir nicht dynamisch ändern, sobald es aber auf jtm.de läuft, passen auch die pfade, das ist jetzt nur in dem `dump` environment so
