### ISSUE TITLE
Semantic UI Icons broken

### ISSUE THREAD

**Issue by ishockwave** [jtm-ev/website#67]
![bildschirmfoto 2016-07-12 um 10 28 14](https://cloud.githubusercontent.com/assets/12819416/16761083/f459c372-481e-11e6-83e2-772c494593d8.png)

**Comment by florianguenther** [comment]
fixed. lag am dump environment, und dass die icon font nicht auf jtm.de online ist.
wird jetzt von localhost geladen.
evtl musst du den asset-pipeline leeren

```
bundle exec rake tmp:clear
```
