### ISSUE TITLE
Öffentliches Profil nicht designed

### ISSUE THREAD

**Issue by ishockwave** [jtm-ev/website#70]

**Comment by ishockwave** [comment]
Ich würde die Rollenübersicht mit der Gallery machen, da kann man Bildunterschrift und Link hinterlegen.
Bei der "Hinter den Kulissen" Rubrik würde ich das ganze zusammenlegen und entweder, falls verfügbar das Team-Bild oder sonst das Haupt Bild des Theaterstücks einblenden. Würde das passen @florianguenther ?

**Comment by florianguenther** [comment]
Find ich nicht gut

**Comment by ishockwave** [comment]
Ok, dann mach ich die Hinter den Kulissen Rubrik mit Bildern wenn verfügbar und den Rest als reine Tabellenauflistung
